version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: age-of-hero-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: age_of_hero
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c log_statement=all
               -c log_destination=stderr
               -c log_min_messages=info
               -c shared_preload_libraries=''

volumes:
  postgres_data: